# Publish a new private GitHub release so lab PCs can auto-update.
# Embeds a read-only GitHub token into the app so lab PCs never type a PAT.
#
# Usage (from repo root):
#   powershell -ExecutionPolicy Bypass -File scripts\publish_release.ps1
#   powershell -ExecutionPolicy Bypass -File scripts\publish_release.ps1 -Version 0.3.2
#
# Token source (first hit wins): BTS_EMBED_GITHUB_TOKEN, scripts/setup_exe/embed_github_token.txt, gh auth token

[CmdletBinding()]
param(
    [string]$Version = "",
    [string]$Notes = "Battery Test Sequencer update"
)

$ErrorActionPreference = "Stop"
$Root = Split-Path $PSScriptRoot -Parent
Set-Location $Root

function Get-CurrentVersion {
    (Get-Content .\VERSION -Raw).Trim()
}

function Set-Version([string]$v) {
    [System.IO.File]::WriteAllText((Join-Path $Root "VERSION"), "$v`n")
    $pyPath = Join-Path $Root "pyproject.toml"
    $py = [System.IO.File]::ReadAllText($pyPath)
    $py2 = [regex]::Replace($py, 'version\s*=\s*"[^"]+"', "version = `"$v`"")
    [System.IO.File]::WriteAllText($pyPath, $py2)
}

function Get-EmbedToken {
    if ($env:BTS_EMBED_GITHUB_TOKEN -and $env:BTS_EMBED_GITHUB_TOKEN.Trim()) {
        return $env:BTS_EMBED_GITHUB_TOKEN.Trim()
    }
    $file = Join-Path $Root "scripts\setup_exe\embed_github_token.txt"
    if (Test-Path $file) {
        $t = (Get-Content $file -Raw).Trim()
        if ($t) { return $t }
    }
    $t = (gh auth token 2>$null)
    if ($t) { return $t.Trim() }
    throw "No GitHub token to embed. Run 'gh auth login', or set BTS_EMBED_GITHUB_TOKEN, or create scripts/setup_exe/embed_github_token.txt"
}

function Write-EmbeddedToken([string]$token) {
    $path = Join-Path $Root "src\bts\_embedded_token.py"
    $env:BTS_EMBED_GITHUB_TOKEN = $token
    python -c @"
from pathlib import Path
import os
token = os.environ.get('BTS_EMBED_GITHUB_TOKEN', '').strip()
if not token:
    raise SystemExit('empty embed token')
path = Path(r'$($path.Replace('\','\\'))')
path.write_text(
    '\"\"\"Auto-generated by publish_release.ps1 — do not edit.\n\n'
    'Read-only GitHub access for private Releases (lab PCs).\n'
    '\"\"\"\n\n'
    f'UPDATE_TOKEN = {token!r}\n',
    encoding='utf-8',
)
print('embedded token ->', path)
"@
}

if (-not $Version) {
    $cur = Get-CurrentVersion
    $parts = $cur.Split(".")
    $parts[2] = [string]([int]$parts[2] + 1)
    $Version = $parts -join "."
}

Write-Host "Publishing v$Version (embedding update token for lab PCs)…" -ForegroundColor Cyan
$token = Get-EmbedToken
Write-EmbeddedToken $token
Set-Version $Version

git add VERSION pyproject.toml .gitignore src/bts/update.py src/bts/ui/main_window.py config/update.yaml scripts/publish_release.ps1
git add -f src/bts/_embedded_token.py
# Pick up other pending app fixes if present
git add -u src requirements.txt 2>$null
git status -sb
git commit -m "release: v$Version — embedded GitHub token for lab auto-update"
git tag -a "v$Version" -m "v$Version"
git push origin HEAD
git push origin "v$Version"

gh release create "v$Version" --title "BTS v$Version" --notes $Notes --repo jancihak99/battery-test-sequencer

Write-Host "Release v$Version published." -ForegroundColor Green
Write-Host "Lab PC: restart BTS — update token is inside the app (no Settings PAT)." -ForegroundColor Green
Write-Host "First-time lab install still needs Setup.exe once; later updates are automatic." -ForegroundColor DarkGray
